import type { NextPage } from 'next'
import Head from 'next/head'
import Container from '@mui/material/Container'
import AmountDisplay from 'components/AmountDisplay/AmountDisplay'
import WalletOverview from 'components/WalletOverview/WalletOverview'
import { useEffect } from 'react'
import { useAppDispatch, useAppSelector } from 'hooks/reduxTypeHook'
import { setBalance, initialBalance } from 'redux/slices/balanceSlice'
import HistoryChart from 'components/HistoryChart/HistoryChart'

const Home: NextPage = () => {
  const dispatch = useAppDispatch()
  const balance = useAppSelector((state) => state.balance)
  
  // Initial balance from localStorage
  useEffect(() => {
    const wallet = localStorage.getItem('wallet')
    if (wallet !== null) {
      dispatch(setBalance(JSON.parse(wallet)))
    }
    dispatch(initialBalance())
  }, [dispatch])

  // Update localStorage when balance is updated
  useEffect(() => {
    if (balance.initialized) {
      localStorage.setItem('wallet', JSON.stringify(balance))
    }
  }, [balance])
  
  return (
    <div>
      <Head>
        <title>Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <WalletOverview />
        <AmountDisplay />
        <HistoryChart />
      </Container>
    </div>
  )
}

export default Home
